### PR TITLE
Made sidebar truly dynamic

### PR DESCRIPTION
**Pull request by kaiser-chris**
Hi @1230james, @Alexedishi and @LordR19,

I have made the sidebar truly dynamic and not rely on pre prepared button placeholders.

To create a new button you first have to create an ideology.
See the following files:

- [common/ideology/example_button.txt](https://github.com/Alexedishi/Vic3-Community-GUI-Framework/compare/main...kaiser-chris:Vic3-Community-GUI-Framework:main#diff-8f995091ce76ed96ec75f70a29ee84dc1862aafb2197e20ad5528a385a97441f)
- [localization/english/com_gui_l_english.yml](https://github.com/Alexedishi/Vic3-Community-GUI-Framework/compare/main...kaiser-chris:Vic3-Community-GUI-Framework:main#diff-c38fe7df9475222c3c463cdabf82e84bbc9875ef1e466d792227659013bb7890)

And then to add it to the sidebar use add_to_global_variable_list anywhere in a plugin.
I have provided an example here:
- [common/history/global/enable_example_button.txt](https://github.com/Alexedishi/Vic3-Community-GUI-Framework/compare/main...kaiser-chris:Vic3-Community-GUI-Framework:main#diff-962e158998336fe1d85877d3d7e1790454f97a2b6fa144c6f57f24c47d9fa6e5)

Please check whether this is an improvement you guys like or not.

Regards,

Chris

### CODE REVIEW

**Comment by kaiser-chris** [comment]
Also fyi the Sidebar now adjusts to the user choosen theme since I use the base game files.

**Comment by kaiser-chris** [comment]
The objectives gui was throwing a lot of errors so I recreated it from scratch and added it to the pull request.

Screenshots:
image
image
image

Now it throws no more errors except these unavoidable ones:
```
[11:17:09][pdx_gui_factory.cpp:1492]: gui/objective_types.gui:3 - Type 'objective_selection_menu' already registered at 'gui/com_gui_objectives.gui'(123)
[11:17:09][pdx_gui_factory.cpp:1492]: gui/objective_types.gui:686 - Type 'game_rules_hbox' already registered at 'gui/com_gui_objectives.gui'(2)
```

**Comment by kaiser-chris** [comment]
I will add a proper documentation on how the sidebar button works when you guys are ok with these changes in general.

**Comment by Alexedishi** [comment]
> I will add a proper documentation on how the sidebar button works when you guys are ok with these changes in general.

I really like this idea and like James said on Discord, abusing ideologies for dynamic buttons is beautiful and horrifying. I'm a gui noob, so I just need some documentation on what changes to make to the scripting for my button to attach it to the sidebar now, since it's not discretely named in the sidebar gui anymore.

**Comment by kaiser-chris** [comment]
@Alexedishi I have moved this pull request to the mod framework project:
https://github.com/Victoria-3-Modding-Co-op/Community-Mod-Framework/pull/13

**Pull request closed without merging**
